export const REPOSITORIES = {
  USER: 'USER_REPOSITORY',
  POOL: 'POOL_REPOSITORY',
  EVENT: 'EVENT_REPOSITORY',
  LIQUIDITTY_PROVIDER: 'LIQUIDITTY_PROVIDER_REPOSITORY',
  DB: 'DATA_SOURCE',
} as const;
